name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: 
  flutter_mobx: 
  provider: 
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  mobx_codegen: 
  build_runner: 

flutter:
  uses-material-design: true
